[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "16"

# Configuración para SPA - Redirige todas las rutas no encontradas a index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 